In [301]:
import numpy as np

In [302]:
# Írj egy olyan fügvényt, ami megfordítja egy 2dimenziós array oszlopait. Bemenetként egy array-t vár.
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
def column_swap(array : np.array):
    array[:, [1, 0]]=array[:, [0, 1]]
    return array
arr = column_swap(np.array([[1,2],[3,4]]))
print(arr)

[[2 1]
 [4 3]]


In [303]:
# Készíts egy olyan függvényt ami összehasonlít két array-t és visszaadja egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7]
# Ki: [1]
# #compare_two_array() egyenlő elemszámúakra kell csak hogy működjön
def compare_two_array(array : np.array, array2 : np.array):
    print(np.where(array == array2)[0])
compare_two_array(np.array([7,8,9]), np.array([9,8,7]))

[1]


In [419]:
# Készíts egy olyan függvényt, ami vissza adja string-ként a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!, 
def get_array_shape(array : np.array):
    print("sor:", array.size // array.shape[-1] , "oszlop:", array.shape[-1] , "melyseg:", array.ndim )

get_array_shape(np.array([2,3,4]))
get_array_shape(np.array([[1,2,3], [4,5,6]]))
get_array_shape(np.array([[[1,2,3], [4,5,6]],[[0,0,0],[0,0,0]]]))

sor: 1 oszlop: 3 melyseg: 1
sor: 2 oszlop: 3 melyseg: 2
sor: 4 oszlop: 3 melyseg: 3


In [305]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenete két lista, az egyikben stringek a másikban floatok vannak. Adja vissza azt az elemet, aminek a legnagyobb a valószínüsége(értéke) a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. # Az ['alma', 'körte', 'szilva'] egy lista!
# Ki: 'szilva'
# eval_classification()
def eval_classification(stringarray : np.array, floatarray : np.array):
    print(stringarray[np.argmax(floatarray)])
eval_classification(np.array(['alma', 'körte', 'szilva']), np.array([0.2, 0.2, 0.6]))

szilva


In [306]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# replace_odd_numbers()
def replace_odd_numbers(array : np.array):
    print(np.where(array%2 != 0, -1, array))
replace_odd_numbers(np.array([1,2,3,4,5,6]))

[-1  2 -1  4 -1  6]


In [307]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

def replace_value(array : np.array, szam):
    print(np.where(array < szam, -1, 1))
replace_value(np.array([1, 2, 5, 0]), 2)

[-1  1  1 -1]


In [308]:
# Készíts egy olyan függvényt, ami egy array értékeit összeszorozza és az eredményt visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

def array_multi(array : np.array):
    print(np.prod(array))
array_multi(np.array([1,2,3,4]))

24


In [309]:
# Készíts egy olyan függvényt, ami egy 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()
def array_multi_2d(array : np.array):  
    print(array[:,0] * array[:,1])
array_multi_2d(np.array([[1, 2], [3, 4]]))

[ 2 12]


In [310]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
def add_border(array : np.array):
    print(np.pad(array, pad_width=1, constant_values=0))
add_border(np.array([[1,2],[3,4]]))

[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


In [311]:
# A KÖTVETKEZŐ FELADATOKHOZ NÉZZÉTEK MEG A NUMPY DATA TYPE-JÁT!

In [312]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD. Térjen vissza egy 'numpy.datetime64' típussal.
# Be:
# Ki: 2017-03-24
def get_act_date():
    return np.datetime64('now','D')
print(get_act_date())


2023-09-22


In [313]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:02:00 óta. Int-el térjen vissza
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
def sec_from_1970():
    dates = np.array([np.datetime64('1970-01-01T00:02:00'), np.datetime64('now')])
    print(np.diff(dates).astype('int'))
sec_from_1970()

[1695390037]
