In [1]:
import numpy as np

In [2]:
# Írj egy olyan fügvényt, ami megfordítja egy 2dimenziós array oszlopait. Bemenetként egy array-t vár.
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

def column_swap(in_array: np.array):
    in_array[:, [1,0]] = in_array[:, [0,1]]
    

ar1 = np.array([[1,2],[3,4]])
column_swap(ar1)
ar1

array([[2, 1],
       [4, 3]])

In [3]:
# Készíts egy olyan függvényt ami összehasonlít két array-t és visszaadja egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

def compare_two_array(in_ar1 : np.array, in_ar2 : np.array ):
    out_array = np.arange(len(in_ar1))[in_ar1==in_ar2]
    return out_array

ar1 = np.array([7,8,9])
ar2 = np.array([9,8,7])
ar3 = compare_two_array(ar1,ar2)
ar3

array([1])

In [4]:
# Készíts egy olyan függvényt, ami vissza adja string-ként a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!, 

def get_array_shape(in_array : np.array):
    shape = in_array.shape
    dimension=len(shape)
    match dimension:
        case 1:
            print(f"sor: {shape[0]}, oszlop: 1, melyseg: 1")
        case 2:
            print(f"sor: {shape[0]}, oszlop: {shape[1]}, melyseg: 1")
        case 3:
            print(f"sor: {shape[0]}, oszlop: {shape[1]} , melyseg: {shape[2]}")


ar1 = np.array([1,2,3])
ar2 = np.array([[1,2,3], [4,5,6]])
ar3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])



get_array_shape(ar1)
get_array_shape(ar2)
get_array_shape(ar3)

sor: 3, oszlop: 1, melyseg: 1
sor: 2, oszlop: 3, melyseg: 1
sor: 2, oszlop: 2 , melyseg: 3


In [5]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenete két lista, az egyikben stringek a másikban floatok vannak. 
# Adja vissza azt az elemet, aminek a legnagyobb a valószínüsége(értéke) a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. # Az ['alma', 'körte', 'szilva'] egy lista!
# Ki: 'szilva'
# eval_classification()

def eval_classification(string_ar : np.array, float_ar: np.array):
    print(string_ar[np.argmax(float_ar)])

fruits = np.array(['alma', 'körte', 'szilva'])
vals =np.array([0.2, 0.2, 0.6])
eval_classification(fruits,vals)

szilva


In [6]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# replace_odd_numbers()

def replace_odd_numbers(in_array: np.array):
    out_array = np.where(in_array%2!=0,-1, in_array)
    return out_array

ar1 = np.array([1,2,3,4,5,6])
ar2 = replace_odd_numbers(ar1)
ar2

array([-1,  2, -1,  4, -1,  6])

In [7]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

def replace_by_value(in_array: np.array, val : int):
    out_array = in_array>=val
    out_array = np.where(out_array==0, -1, out_array )
    return out_array

ar1 = np.array([1, 2, 5, 0])
ar2 = replace_by_value(ar1,2)
ar2

array([-1,  1,  1, -1])

In [20]:
# Készíts egy olyan függvényt, ami egy array értékeit összeszorozza és az eredményt visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

def array_multi(in_array : np.array):
    res = np.prod(in_array)
    return res

ar1 = np.array([1,2,3,4])
result=array_multi(ar1)
result

24

In [22]:
# Készíts egy olyan függvényt, ami egy 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

def array_multi_2d(dd_array: np.array):
    dim = len(np.shape(dd_array))
    if dim < 3:
        res_array = np.prod(dd_array,axis=1)
    else:
        print("Error: input array was not a 2D array!")
    return res_array

ar1 = np.array([[1, 2], [3, 4]])
ar2 = array_multi_2d(ar1)
ar2

array([ 2, 12])

In [26]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()

def add_border(in_array: np.array):
    x, y = in_array.shape[0]+2, in_array.shape[1]+2
    out_array = np.zeros((x,y))
    out_array[1:x-1, 1:y-1] = in_array
    return out_array

ar1 = np.array([[1,2],[3,4]])
ar2 = add_border(ar1)
ar2

array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 3., 4., 0.],
       [0., 0., 0., 0.]])

In [11]:
# A KÖTVETKEZŐ FELADATOKHOZ NÉZZÉTEK MEG A NUMPY DATA TYPE-JÁT!

In [31]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD. Térjen vissza egy 'numpy.datetime64' típussal.
# Be:
# Ki: 2017-03-24
# get_act_date()
import datetime as dt

def get_act_date():
    now = np.datetime64(dt.date.today())
    print(now)

get_act_date()

2023-09-22


In [40]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:02:00 óta. Int-el térjen vissza
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()

def sec_from_1970():
    epoch = dt.datetime(1970,1,1,0,2,0,0)
    now = dt.datetime.now()
    delta = round((now - epoch).total_seconds())
    print(delta)

sec_from_1970()

1695417230
